version: "3.3"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "quiz_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data:/home/postgres/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped

  fastapi:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    command: ["sh", "-c", "ulimit -s 65535 && python start_website"]
    depends_on:
      - postgres
